#!/usr/bin/python3

import sys
import time
import json
import socket


def rest_call_example():
    import requests
    from pprint import pprint

    ret = requests.request(
        url='http://10.1.0.20/sony/system',
        data=json.dumps({"version": "1.0", "method": "getRemoteControllerInfo", "id": 50, "params": []}),
        headers={
            'User-Agent': b'HTTPie/2.4.0',
            'Accept': b'application/json, */*;q=0.5',
            'Content-Type': b'application/json',
            'X-Auth-PSK': b'adminff'
        },
        method='POST',
        params={},
    )

    ir_commands = {d['name']: d['value'] for d in ret.json()['result'][1]}
    pprint(ir_commands)


simple_ip_cmds = {
    "Display":       b"*SC IRCC 0000000000000005",
    "Home":          b"*SC IRCC 0000000000000006",
    "Options":       b"*SC IRCC 0000000000000007",
    "Return":        b"*SC IRCC 0000000000000008",
    "Up":            b"*SC IRCC 0000000000000009",
    "Down":          b"*SC IRCC 0000000000000010",
    "Right":         b"*SC IRCC 0000000000000011",
    "Left":          b"*SC IRCC 0000000000000012",
    "Confirm":       b"*SC IRCC 0000000000000013",
    "Red":           b"*SC IRCC 0000000000000014",
    "Green":         b"*SC IRCC 0000000000000015",
    "Yellow":        b"*SC IRCC 0000000000000016",
    "Blue":          b"*SC IRCC 0000000000000017",
    "Num1":          b"*SC IRCC 0000000000000018",
    "Num2":          b"*SC IRCC 0000000000000019",
    "Num3":          b"*SC IRCC 0000000000000020",
    "Num4":          b"*SC IRCC 0000000000000021",
    "Num5":          b"*SC IRCC 0000000000000022",
    "Num6":          b"*SC IRCC 0000000000000023",
    "Num7":          b"*SC IRCC 0000000000000024",
    "Num8":          b"*SC IRCC 0000000000000025",
    "Num9":          b"*SC IRCC 0000000000000026",
    "Num0":          b"*SC IRCC 0000000000000027",
    "Volume Up":     b"*SC IRCC 0000000000000030",
    "Volume Down":   b"*SC IRCC 0000000000000031",
    "Mute":          b"*SC IRCC 0000000000000032",
    "Channel Up":    b"*SC IRCC 0000000000000033",
    "Channel Down":  b"*SC IRCC 0000000000000034",
    "Subtitle":      b"*SC IRCC 0000000000000035",
    "DOT":           b"*SC IRCC 0000000000000038",
    "Picture Off":   b"*SC IRCC 0000000000000050",
    "Wide":          b"*SC IRCC 0000000000000061",
    "Jump":          b"*SC IRCC 0000000000000062",
    "Sync Menu":     b"*SC IRCC 0000000000000076",
    "Forward":       b"*SC IRCC 0000000000000077",
    "Play":          b"*SC IRCC 0000000000000078",
    "Rewind":        b"*SC IRCC 0000000000000079",
    "Prev":          b"*SC IRCC 0000000000000080",
    "Stop":          b"*SC IRCC 0000000000000081",
    "Next":          b"*SC IRCC 0000000000000082",
    "Pause":         b"*SC IRCC 0000000000000084",
    "Flash Plus":    b"*SC IRCC 0000000000000086",
    "Flash Minus":   b"*SC IRCC 0000000000000087",
    "TV Power":      b"*SC IRCC 0000000000000098",
    "Audio":         b"*SC IRCC 0000000000000099",
    "Input":         b"*SC IRCC 0000000000000101",
    "Sleep":         b"*SC IRCC 0000000000000104",
    "Sleep Timer":   b"*SC IRCC 0000000000000105",
    "Video 2":       b"*SC IRCC 0000000000000108",
    "Picture Mode":  b"*SC IRCC 0000000000000110",
    "Demo Surround": b"*SC IRCC 0000000000000121",
    "Action Menu":   b"*SC IRCC 0000000000000129",
    "Help":          b"*SC IRCC 0000000000000130",

    "HDMI 1":        b"*SC INPT 00000001 0000 0001",
    "HDMI 2":        b"*SC INPT 00000001 0000 0002",
    "HDMI 3":        b"*SC INPT 00000001 0000 0003",
    "HDMI 4":        b"*SC INPT 00000001 0000 0004",

    "Power Off":     b"*SC POWR 0000000000000000",
    "Power On":      b"*SC POWR 0000000000000001",
}

simple_ip_cmds = {
    key.replace(' ', '').upper(): val.replace(b" ", b"")
                                             for key, val in simple_ip_cmds.items()
}


HOST = '10.1.0.20'
PORT = 20060


def send_ir_command(*args):
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.connect((HOST, PORT))
        for a in args:
            if isinstance(a, str):
                a = a.replace(' ', '').upper()
                s.sendall(simple_ip_cmds[a] + b'\n')
                data = s.recv(24)
                print(data)
            elif isinstance(a, (int, float)):
                time.sleep(a)


def set_backlight(val):
    send_ir_command(
        # Picture
        'Options', 1, 'Down', .1, 'Confirm', 3,

        # Backlight
        'Down', .1, 'Down', .1, 'Down', .1, 'Confirm', .5,

        # Set backlight to zero
        'Left', .1, 'Left', .1, 'Left', .1, 'Left', .1, 'Left', .1,
        'Left', .1, 'Left', .1, 'Left', .1, 'Left', .1, 'Left', .1,
    )

    for i in range(val):
        send_ir_command('Right', .1)

    send_ir_command('Return', .5, 'Return', .5)  # exit


def main(args):
    if len(args) < 2:
        print("Usage:", args[0], "<cmd> [args]")
        print("   ", "sb, set-backlight <int 1-10>")
        return 1

    if args[1] in ('sb', 'set-backlight'):
        set_backlight(int(args[2]))

    elif args[1].upper() in simple_ip_cmds:
        send_ir_command(args[1].upper(), .5)

    else:
        raise ValueError(args[1])

    return 0


if __name__ == "__main__":
    main(sys.argv)
